##
## EPITECH PROJECT, 2023
## MAKEFILE MAIN
## File description:
## A program that do simple operation.
##

.PHONY: all clean fclean re

all:
	cp zappy_ai.sh ../zappy_ai

clean:
	rm -rf __pycache__
	rm -rf bot/__pycache__
	rm -rf bot/helper/__pycache__
	rm -rf network/__pycache__

fclean:	clean
	rm ../zappy_ai

re:	fclean all
