##
## EPITECH PROJECT, 2023
## MAKEFILE MAIN
## File description:
## A program that do simple operation.
##

.PHONY: all clean fclean re

all:
	cp zappy_ai.py ../zappy_ai

clean:

fclean:	clean
	rm ../zappy_ai

re:	fclean all
